# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TWU' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    pod 'Firebase/Auth'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'

    # Pods for TWS
#    source 'https://github.com/CocoaPods/Specs.git'
#    platform :ios, '8.0'
#    use_frameworks!
#    
#    pod 'Material', '~> 2.0'
    # Pods for TWU
    
end
